### PR TITLE
Macro to create summary data

### PR DESCRIPTION
**Pull request by maggiesu0725**

### CODE REVIEW

**Comment by maggiesu0725** [comment]
@rpitingolo ready for review

**Comment by rpitingolo** [comment]
@maggiesu0725 thanks. Program looks good. One outstanding question I have is about the MOEs. 
@ptatian I assume you want the MOEs to be on the summary files?

**Comment by ptatian** [comment]
@rpitingolo Well, officially, I should say yes. :+1: But, I don't think %Create_all_summary_from_tracts() is currently configured to deal with MOEs. I don't think that would be a difficult change, however. You'd just have to add those parameters and pass them through to %Transform_geo_data().

**Comment by lhendey** [comment]
@rpitingolo @ptatian - if it matters the i think the MOEs are generally quite small - they are different than the ACS MOEs - they are indicating the model fit. from the guide: " The estimates will have low reported margins of error because the model fits the underlying data well overall, but this does not necessarily mean the values are accurate for any specific neighborhood"

**Comment by ptatian** [comment]
I'm fine with omitting the MOEs from the summary files.

**Comment by rpitingolo** [comment]
@ptatian thanks. 
@maggiesu0725 you can go ahead and merge, sync and batch submit.

**Pull request merged**
